version: '3.5'
services:

  traefik:
    build:
      context: ./
      dockerfile: Dockerfile.traefik
    ports:
      - "0.0.0.0:80:80"
      - "0.0.0.0:443:443"
    expose:
      - "8080"
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - reverseproxy:/mytraefik
    networks:
      reverseproxy:
        aliases:
         - reverseproxy
         - traefik
    labels:
      # librehost labels must be present on all services
      # librehost.stack.id must be equal the name of the repository
      - "librehost.stack.id=reverseproxy"
      - "librehost.stack.name=${COMPOSE_PROJECT_NAME:?err}"
      - "librehost.stack.domains=${LIBREHOST_STACK_DOMAINS:?err}"
      - "librehost.stack.json=${LIBREHOST_STACK_JSON:?err}"
      - "librehost.stack.service.number=1"
      - "librehost.stack.service.name=${COMPOSE_PROJECT_NAME:?err}_traefik"
      - "librehost.stack.service.version=${LIBREHOST_STACK_SERVICE_1_VERSION:-latest}"
    #command: --logLevel=DEBUG
    healthcheck:
      test: ["CMD", "traefik", "healthcheck"]
      interval: 10s
      timeout: 30s
      retries: 3
      #start_period: 5s

volumes:
  reverseproxy:

networks:
  reverseproxy:
      name: reverseproxy # named networks will not get removed on container update/removal
  
