version: '3.5'
services:

  traefik:
    build:
      context: ./
      dockerfile: Dockerfile.traefik
    ports:
      - "0.0.0.0:80:80"
      - "0.0.0.0:443:443"
    expose:
      - "8080"
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - reverseproxy:/mytraefik
    networks:
      reverseproxy:
        aliases:
         - reverseproxy
         - traefik
    labels:
      - "librehost.stack.id=reverseproxy" # do not change
      - "librehost.stack.name=${COMPOSE_PROJECT_NAME:?err}" # do not change
      - "librehost.container.name=${COMPOSE_PROJECT_NAME:?err}_traefik" # do not change
      - "librehost.form.email=${LIBREHOST_FORM_EMAIL:?err}"
    #command: --logLevel=DEBUG
    healthcheck:
      test: ["CMD", "traefik", "healthcheck"]
      interval: 10s
      timeout: 30s
      retries: 3
      #start_period: 5s

volumes:
  reverseproxy:

networks:
  reverseproxy:
      name: reverseproxy # named networks will not get removed on container update/removal
  
